### ISSUE TITLE
Question about activeTaskCount

### ISSUE THREAD

**Issue by TheLastTech** [WesVanVugt/promise-pool-executor#8]
What is the difference between activeTaskCount and activePromiseCount?

thanks for writing this btw,

For instance, I want to display

OpenSlots: X
Active: Y  
InQueue: Z

However, which is which?

**Comment by WesVanVugt** [comment]
`pool.activeTaskCount` is the number of tasks which are not in the `terminated` state (they're still running).
`pool.activePromiseCount` is the number of promises which are still running.

If you set up your tasks so that you only make one promise at a time (`task.concurrencyLimit` of 1, or `task.invocationLimit` of 1), then the numbers should always be the same unless tasks are restricted from creating promises by pool or group limits.

I am not entirely sure what you are creating, but it sounds like you could use `pool.freeSlots` and `pool.activePromiseCount` for X and Y. If you are only running one promise per task, you could use `pool.activeTaskCount` - `pool.activePromiseCount` for Z, since any queued tasks will not have active promises if they are waiting to run due to pool or group limits.
